name: Auto Update Compile Script

on:
  push:
    branches:
      - main
    paths-ignore:
      - "bin/**"
  schedule:
    - cron: "0 5 * * 0"

jobs:
  FetchUpdates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Push Results
        working-directory: ${{ github.workspace }}
        env:
          # This URL get's the latest information - Do not change
          REPOSITORY_URL: "https://raw.githubusercontent.com/zibdie/heroku-info-api/main/api/heroku-stack-api.json"
        run: |
          git pull --all
          git stash
          git stash clear
          pip3 install -r ./requirements.txt
          python3 ./update.py
          git add --force .
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git commit -m "Weekly Auto Update via GitHub Actions"
          git push -u origin $(git rev-parse --abbrev-ref HEAD)
